# Generated by Django 4.2 on 2024-12-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestFile',
            new_name='TestFileModel',
        ),
    ]
